export const emptyItemParams = {
  employee_id: '',
  title: '',
  value: '',
  description: '',
  subtype: 'resource',
  source_sheet: '',
  is_draft: false,
  room: '',
  fio: '',
  login: '',
  mac_address: '',
  user_matches_login: false,
  valid_until: '',
  file_name: '',
  file_mime_type: '',
  file_data: '',
  private_file_name: '',
  private_file_mime_type: '',
  private_file_data: '',
  private_valid_until: '',
  remove_public_file: false,
  remove_private_file: false,
  department_id: '',
  department: '',
  location_id: '',
  organization: '',
  is_external: false,
  accounting_flag: false,
  name: '',
  position: '',
  email: '',
  phone: '',
  internal: '',
  mobile: '',
  note: '',
  refilled_count: '0',
  new_count: '0',
  critical_limit: '2',
  model_name: '',
  cartridge_name: '',
  cartridge_type_name: ''
}

export const createEmptyItemParams = () => ({ ...emptyItemParams })
