import type { Prisma } from '@prisma/client'

type Timestamp = Date | string

export interface SeedBackupSnapshot {
  generatedAt: string
  users: Array<{
    id: string
    email: string
    name: string | null
    avatar: string | null
    createdAt: Timestamp
    updatedAt: Timestamp
  }>
  projects: Array<{
    id: string
    name: string
    slug: string
    url: string
    status: string
    siteType: string
    description: string | null
    thumbnail: string | null
    userId: string
    content: Prisma.JsonValue | null
    settings: Prisma.JsonValue | null
    createdAt: Timestamp
    updatedAt: Timestamp
  }>
  pages: Array<{
    id: string
    projectId: string
    slug: string
    title: string
    content: Prisma.JsonValue
    updatedAt: Timestamp
  }>
  images: Array<{
    id: string
    projectId: string
    url: string
    path: string
    size: number
    mimeType: string
    alt: string | null
    createdAt: Timestamp
  }>
  builds: Array<{
    id: string
    projectId: string
    status: string
    logs: string | null
    triggeredBy: string | null
    startedAt: Timestamp
    endedAt: Timestamp | null
  }>
}

function serializeSnapshot(snapshot: SeedBackupSnapshot) {
  return JSON.stringify(snapshot, null, 2)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

export function createSeedBackup(snapshot: SeedBackupSnapshot) {
  return `// Generated by Admin Panel on ${snapshot.generatedAt}.
// Contains database records and media metadata. Files from uploads/ must be backed up separately.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient, Prisma } = require('@prisma/client')

const db = new PrismaClient()
const snapshot = ${serializeSnapshot(snapshot)}

const nullableJson = (value) => value === null ? Prisma.DbNull : value

function mappedId(map, sourceId, entity) {
  const value = map.get(sourceId)
  if (!value) throw new Error(\`Missing restored \${entity} for source id \${sourceId}\`)
  return value
}

async function main() {
  console.log('Restoring Admin Panel content backup...')

  const userIds = new Map()
  for (const user of snapshot.users) {
    const existing = await db.user.findFirst({
      where: { OR: [{ id: user.id }, { email: user.email }] },
      select: { id: true },
    })
    const data = {
      email: user.email,
      name: user.name,
      avatar: user.avatar,
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    }
    const restored = existing
      ? await db.user.update({ where: { id: existing.id }, data })
      : await db.user.create({ data: { id: user.id, ...data } })
    userIds.set(user.id, restored.id)
  }

  const projectIds = new Map()
  for (const project of snapshot.projects) {
    const existing = await db.project.findFirst({
      where: { OR: [{ id: project.id }, { slug: project.slug }] },
      select: { id: true },
    })
    const data = {
      name: project.name,
      slug: project.slug,
      url: project.url,
      status: project.status,
      siteType: project.siteType,
      description: project.description,
      thumbnail: project.thumbnail,
      userId: mappedId(userIds, project.userId, 'user'),
      content: nullableJson(project.content),
      settings: nullableJson(project.settings),
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
    }
    const restored = existing
      ? await db.project.update({ where: { id: existing.id }, data })
      : await db.project.create({ data: { id: project.id, ...data } })
    projectIds.set(project.id, restored.id)
  }

  for (const page of snapshot.pages) {
    const projectId = mappedId(projectIds, page.projectId, 'project')
    const existing = await db.page.findFirst({
      where: { OR: [{ id: page.id }, { projectId, slug: page.slug }] },
      select: { id: true },
    })
    const data = {
      projectId,
      slug: page.slug,
      title: page.title,
      content: page.content,
      updatedAt: page.updatedAt,
    }
    if (existing) await db.page.update({ where: { id: existing.id }, data })
    else await db.page.create({ data: { id: page.id, ...data } })
  }

  for (const image of snapshot.images) {
    const data = {
      projectId: mappedId(projectIds, image.projectId, 'project'),
      url: image.url,
      path: image.path,
      size: image.size,
      mimeType: image.mimeType,
      alt: image.alt,
      createdAt: image.createdAt,
    }
    await db.image.upsert({
      where: { id: image.id },
      update: data,
      create: { id: image.id, ...data },
    })
  }

  for (const build of snapshot.builds) {
    const data = {
      projectId: mappedId(projectIds, build.projectId, 'project'),
      status: build.status,
      logs: build.logs,
      triggeredBy: build.triggeredBy,
      startedAt: build.startedAt,
      endedAt: build.endedAt,
    }
    await db.build.upsert({
      where: { id: build.id },
      update: data,
      create: { id: build.id, ...data },
    })
  }

  console.log(JSON.stringify({
    restored: {
      users: snapshot.users.length,
      projects: snapshot.projects.length,
      pages: snapshot.pages.length,
      images: snapshot.images.length,
      builds: snapshot.builds.length,
    },
    mediaFiles: 'not included; restore uploads/ separately',
  }))
}

main()
  .catch((error) => {
    console.error('Failed to restore content backup:', error)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
`
}
